name       : ghex
version    : 3.18.0
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/ghex/3.18/ghex-3.18.0.tar.xz : c5b1eb50a8dd1334880b37617871498b778ea137f79bb43894ec68e4f63dc925
license    :
    - GPL-2.0
    - GFDL-1.1
summary    : Gnome Hex Editor
description: |
    Gnome Hex Editor
builddeps  :
    - pkgconfig(gail-3.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
