name       : ghex
version    : '42.2'
release    : 6
source     :
    - https://download.gnome.org/sources/ghex/42/ghex-42.2.tar.xz : 45de8e6b8a1f31de5a9910be18c07f09a328d87538df80403aec5af8817c9631
license    :
    - GPL-2.0-or-later
    - GFDL-1.1-only
summary    : Gnome Hex Editor
component  : desktop.gnome
description: |
    Gnome Hex Editor
builddeps  :
    - pkgconfig(gtk4)
    - desktop-file-utils
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
