name       : ghex
version    : 3.18.4
release    : 4
source     :
    - https://download.gnome.org/sources/ghex/3.18/ghex-3.18.4.tar.xz : c2d9c191ff5bce836618779865bee4059db81a3a0dff38bda3cc7a9e729637c0
license    :
    - GPL-2.0-or-later
    - GFDL-1.1-only
summary    : Gnome Hex Editor
component  : desktop.gnome
description: |
    Gnome Hex Editor
builddeps  :
    - pkgconfig(gail-3.0)
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
