name       : ghex
version    : '44.1'
release    : 9
source     :
    - https://download.gnome.org/sources/ghex/44/ghex-44.1.tar.xz : 404bdf649eaa13922a80ae32f19fe40e71f0ee0f461c45edac72888a00ead6c2
homepage   : https://wiki.gnome.org/Apps/Ghex
license    :
    - GPL-2.0-or-later
    - GFDL-1.1-only
component  : desktop.gnome
summary    : GHex - a hex editor for GNOME
description: |
    GHex allows the user to load data from any file, view and edit it in either hex or ASCII. Useful for debugging problems with object code or encodings. Also used by kids who cheat at computer games, by adding score or lives to saved games.
builddeps  :
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
