name       : ghex
version    : '43.0'
release    : 7
source     :
    - https://download.gnome.org/sources/ghex/43/ghex-43.0.tar.xz : 866c0622c66fdb5ad2a475e9cfcccb219a1c6431f009acb2291d43f2140b147e
homepage   : https://wiki.gnome.org/Apps/Ghex
license    :
    - GPL-2.0-or-later
    - GFDL-1.1-only
component  : desktop.gnome
summary    : GHex - a hex editor for GNOME
description: |
    GHex allows the user to load data from any file, view and edit it in either hex or ASCII. Useful for debugging problems with object code or encodings. Also used by kids who cheat at computer games, by adding score or lives to saved games.
builddeps  :
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
